rag_task:
  variables: ["query", "chat_history_context"]
  description: >
    Rispondi esclusivamente alla seguente richiesta dell’utente: "{{query}}".
    Se serve contesto sulla conversazione precedente per comprendere la richiesta attuale dello user, usalo: "{{chat_history_context}}".
    Usa esclusivamente i tool disponibili (HybridSearchTool e list_qdrant_collections_tool)
    per interrogare la knowledge base locale (RAG del libro caricato dallo user in formato PDF).
    - Seleziona la Qdrant Collection più pertinente alla query dello user.
    - Recupera i contenuti più pertinenti alla query dalla Qdrant Collection selezionata.
    - Sintetizza le informazioni rilevanti in una risposta chiara e fedele ai documenti.

    Parla e rispondi nella stessa lingua utilizzata dall’utente nella query.
    Non aggiungere dettagli non presenti nei documenti. 
    Se non ci sono informazioni rilevanti, dichiara esplicitamente che non sono stati trovati risultati rilevanti.
  expected_output: >
    Una risposta chiara, concisa e fedele ai documenti del RAG,
    o un messaggio che indica l’assenza di risultati pertinenti.
  agent: rag_agent


search_task:
  variables: ["query", "chat_history_context"]
  description: >
    Esegui una ricerca online per la seguente richiesta: "{{query}}".
    Se serve contesto sulla conversazione precedente per comprendere la richiesta attuale dello user, usalo: "{{chat_history_context}}".
    - Estrai e riassumi i risultati più rilevanti.
    - Ignora contenuti ridondanti o irrilevanti.
    - Evidenzia le informazioni chiave in modo sintetico.
    - Fornisci un elenco delle fonti principali utilizzate.

    Parla e rispondi nella stessa lingua utilizzata dall’utente nella query.
    Se non vengono trovati dati utili, dichiara esplicitamente che non ci sono risultati pertinenti.
  expected_output: >
    Una risposta sintetica e affidabile basata sui risultati web,
    accompagnata da una lista delle fonti principali.
  agent: search_agent


synthesizer_task:
  variables: ["query", "chat_history_context"]
  description: >
    Ricevi i risultati di due attività precedenti:
    - L’output del RAG, che fornisce informazioni dai documenti della knowledge base locale (RAG del libro caricato dallo user in formato PDF).
    - L’output della ricerca online, che offre dati aggiornati da fonti esterne.

    Il tuo compito è:
    - Integrare i due insiemi di informazioni.
    - Eliminare ridondanze e contraddizioni, riportando solo i concetti più utili.
    - Evidenziare punti di convergenza e divergenza tra le due fonti, se presenti, specificando se necessario come 
      "nei file caricati sono presenti informazioni che dicono X, mentre dalle fonti web risulta Y".
    - Formulare una risposta finale chiara, ben strutturata e mirata alla query dell’utente: "{{query}}".
    - Se serve contesto sulla conversazione precedente per comprendere la richiesta attuale dello user, usalo: "{{chat_history_context}}".

    Riferisciti sempre ai documenti della RAG come "I libri caricati dall'utente", o "i file caricati dall'utente", ma non come "RAG" (rimani in ambito letterario).
    Parla e rispondi nella stessa lingua utilizzata dall’utente nella query.
    Se entrambe le fonti non contengono dati rilevanti, dichiara onestamente che nè sui files locali nè online sono state trovate informazioni utili.
  expected_output: >
    Un riassunto unico, conciso e focalizzato, che integra i risultati del RAG e della ricerca online
    per rispondere in modo completo alla query dell’utente, mettendo in evidenza eventuali discrepanze nelle due fonti di informazioni.
  context: 
    - rag_task
    - search_task
  agent: synthesizer_agent
  