scene_extraction_task:
  variables: ["topic", "chat_history_context"]
  description: >
    Analyze the provided text answering the following user query: '{topic}'. 
    Se serve contesto sulla conversazione precedente per comprendere la richiesta attuale dello user, usalo: "{{chat_history_context}}".
    Identify a scene that can be clearly depicted in an image.
    Ensure the scene represents what the user asked for in {topic}, but remove or modify any copyrighted fictional characters (including their names), brand names, or recognizable intellectual property to avoid copyright issues.
  expected_output: >
    A concise description of a single scene suitable for image generation, highlighting key visual elements.
  agent: scene_extractor

image_prompt_task:
  description: >
    Craft a detailed, realistic prompt for generating an image based on the scene
    extracted by the previous agent. The prompt should be visually descriptive,
    clear, and suitable for use with image generation tools. When creating the prompt,
    ensure that it does not include any copyrighted characters, brand names, or
    recognizable intellectual property: they should be removed or modified.
    Focus on original, generic, or inspired
    elements to avoid any copyright issues while maintaining the scene's essence.
  expected_output: >
    A well-structured image prompt that accurately conveys the scene and its visual details for image generation.
  context:
    - scene_extraction_task  
  agent: image_prompt_generator

image_creation_task:
  description: >
    Use the provided image prompt and tool to generate only one realistic image that explains the topic.
    Modify any element that could be protected by copyright, but keeping the essence of the prompt.
    Ensure the image is engaging and accessible for a wide audience.
    Save the image in a folder named 'output'.
    The image generation tool requires ONLY two parameters: the prompt and the path to save the image.
    After generating the image, answer only with a string object containing the path to the generated image file, without adding any other kind of text.
    Example format: output\generated_123456.png
  expected_output: >
    The path to the generated image file.
  context: 
    - image_prompt_task
  agent: image_creator